# Generated by Django 2.1 on 2019-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
