# Generated by Django 2.1 on 2019-09-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190905_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Дата выполнения'),
        ),
    ]
