# Generated by Django 2.1 on 2019-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190906_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Детали'),
        ),
    ]
