# Generated by Django 2.1 on 2019-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190907_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Дата выполнения'),
        ),
    ]
