# Generated by Django 2.2 on 2019-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190916_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(max_length=5000, verbose_name='Детали'),
        ),
    ]
